import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from "@/app/Header";
import './global.scss'
import Footer from './Footer';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" data-theme="emerald">
      <body className={inter.className} >
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
