import type { Metadata } from 'next'
import { roboto } from './fonts'
import Header from "@/components/Header/Header";
import './global.scss'
import Footer from './Footer';
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru" data-theme="emerald">

        <body className={roboto.className} >
      <Header/>
      <AppRouterCacheProvider> {children} </AppRouterCacheProvider>
      <Footer/>
      </body>
    </html>
  )
}
